### ISSUE TITLE
False meal

### ISSUE THREAD

**Issue by hroncok** [tomaskadlec/d2s#29]
Today, I see a false meal in Na Urale list:

    zdarma. Nové stránky na www.drest.cz	- Kč

**Comment by tomaskadlec** [comment]
Well, parsers have their flaws and do not expect much creativity from webmasters. It should be easily fixed.

**Comment by hroncok** [comment]
Thanks for the quick fix.

**Comment by tomaskadlec** [comment]
New version with the fix has been just deployed to production.
