### ISSUE TITLE
unknown reffered date

### ISSUE THREAD

**Issue by HalisCz** [tomaskadlec/d2s#46]
There is no timestamp on the page determining validity of the menu, so there is no way how to distinguish which day menu is shown (especially around midnight).

**Comment by tomaskadlec** [comment]
It should be easy to done. Each cache entry has timestamp now and whole thing is to show it in UI.

**Comment by tomaskadlec** [comment]
Each menu has a footer now. There is date and time when menu was retrived. Also there is a button  you can use to reload menu (e.g if it is invalid).
