### ISSUE TITLE
Outdated menu

### ISSUE THREAD

**Issue by KaschiCZE** [tomaskadlec/d2s#55]
Sometimes happens that it api doesn't load new menu and leaves old one there. Usually happens with U Pětníka. Like today. 
![image](https://cloud.githubusercontent.com/assets/11159274/14678245/3d58a89a-0715-11e6-90b1-cdb57b745465.png)
![image](https://cloud.githubusercontent.com/assets/11159274/14678262/4edea98e-0715-11e6-9c32-6f3a12ac0384.png)

**Comment by tomaskadlec** [comment]
It may happen. Menu is loaded once a day with the first request. Loaded menu is stored in cache (till 01:00 AM next day). You are able to reload menu now. Also date an time is shown under each menu so you know when the menu was loaded. 

The issue refers partially to the same problem as #46.
